version: 2

sources:
  - name: raw
    database: master
    schema: dbo
    tables:
      - name: raw_data

schemas:
  - name: fct
    description: Fact tables
  - name: stg
    description: Staging tables, used for intermediary steps
  - name: mrt
    description: Mart tables
  - name: dim
    description: Dimension tables

models:
  - name: orders
    description: "The order Dimension"
    config:
      materialized: table
    columns:
      - name: order_id
        tests:
          - unique:
              config:
                severity: error
  - name: date
    description: "The Date Dimension"
    config:
      materialized: table
    columns:
      - name: date_id
        tests:
          - unique:
              config:
                severity: error
